/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import ILink from "./models/ILink";
export { default as ILink } from "./models/ILink";
export namespace Components {
    interface BwBtn {
        /**
          * @default "#"
         */
        "link": string;
        /**
          * @default "Name"
         */
        "name": string;
    }
    interface BwCard {
        "description": string;
        /**
          * @default 200
         */
        "descriptionLength": number;
        "imgAlt": string;
        "imgSrc": string;
        /**
          * @default '#'
         */
        "link": string;
        "name": string;
        /**
          * @default true
         */
        "populate": boolean;
        /**
          * @default true
         */
        "showBtn": boolean;
        /**
          * @default 'Tags:'
         */
        "tagTitle": string;
        "tags": string[];
    }
    interface BwContainer {
        /**
          * @default false
         */
        "grid": boolean;
        /**
          * @default "0px"
         */
        "mg": string;
        /**
          * @default "10px"
         */
        "pd": string;
        /**
          * @default false
         */
        "primary": boolean;
    }
    interface BwInput {
        /**
          * @default '0px'
         */
        "boxMg": string;
        "boxMgH": string;
        "boxMgV": string;
        /**
          * @default '0px'
         */
        "boxPd": string;
        "boxPdH": string;
        "boxPdV": string;
        /**
          * @default 5
         */
        "col": number;
        /**
          * @default 'Name'
         */
        "label": string;
        /**
          * @default false
         */
        "labelBold": boolean;
        /**
          * @default '1.5rem'
         */
        "labelSize": string;
        /**
          * @default '0px'
         */
        "mg": string;
        /**
          * @default '5px'
         */
        "pd": string;
        /**
          * @default 'Type Something'
         */
        "placeholder": string;
        /**
          * @default 5
         */
        "row": number;
        /**
          * @default '1rem'
         */
        "size": string;
        /**
          * @default false
         */
        "textarea": boolean;
        /**
          * @default 'type'
         */
        "type": string;
    }
    interface BwModal {
        /**
          * @default false
         */
        "isOpen": boolean;
        /**
          * @default ''
         */
        "name": string;
    }
    interface BwNav {
        /**
          * @default { name: 'Navbar', link: '#' }
         */
        "homeLink": ILink;
        /**
          * @default '0px'
         */
        "mg": string;
        /**
          * @default [     { name: 'Search', link: '#' },     { name: 'Manage', link: '#' },     { name: 'About', link: '#' },     { name: 'Profile', link: '#' },   ]
         */
        "navLinks": Array<ILink>;
        /**
          * @default '10px'
         */
        "pd": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
}
export interface BwBtnCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBwBtnElement;
}
export interface BwInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBwInputElement;
}
export interface BwModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBwModalElement;
}
declare global {
    interface HTMLBwBtnElementEventMap {
        "Click": void;
    }
    interface HTMLBwBtnElement extends Components.BwBtn, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBwBtnElementEventMap>(type: K, listener: (this: HTMLBwBtnElement, ev: BwBtnCustomEvent<HTMLBwBtnElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBwBtnElementEventMap>(type: K, listener: (this: HTMLBwBtnElement, ev: BwBtnCustomEvent<HTMLBwBtnElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBwBtnElement: {
        prototype: HTMLBwBtnElement;
        new (): HTMLBwBtnElement;
    };
    interface HTMLBwCardElement extends Components.BwCard, HTMLStencilElement {
    }
    var HTMLBwCardElement: {
        prototype: HTMLBwCardElement;
        new (): HTMLBwCardElement;
    };
    interface HTMLBwContainerElement extends Components.BwContainer, HTMLStencilElement {
    }
    var HTMLBwContainerElement: {
        prototype: HTMLBwContainerElement;
        new (): HTMLBwContainerElement;
    };
    interface HTMLBwInputElementEventMap {
        "changedValue": { oldValue: string; newValue: string };
    }
    interface HTMLBwInputElement extends Components.BwInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBwInputElementEventMap>(type: K, listener: (this: HTMLBwInputElement, ev: BwInputCustomEvent<HTMLBwInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBwInputElementEventMap>(type: K, listener: (this: HTMLBwInputElement, ev: BwInputCustomEvent<HTMLBwInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBwInputElement: {
        prototype: HTMLBwInputElement;
        new (): HTMLBwInputElement;
    };
    interface HTMLBwModalElementEventMap {
        "modalClosed": void;
    }
    interface HTMLBwModalElement extends Components.BwModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBwModalElementEventMap>(type: K, listener: (this: HTMLBwModalElement, ev: BwModalCustomEvent<HTMLBwModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBwModalElementEventMap>(type: K, listener: (this: HTMLBwModalElement, ev: BwModalCustomEvent<HTMLBwModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBwModalElement: {
        prototype: HTMLBwModalElement;
        new (): HTMLBwModalElement;
    };
    interface HTMLBwNavElement extends Components.BwNav, HTMLStencilElement {
    }
    var HTMLBwNavElement: {
        prototype: HTMLBwNavElement;
        new (): HTMLBwNavElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "bw-btn": HTMLBwBtnElement;
        "bw-card": HTMLBwCardElement;
        "bw-container": HTMLBwContainerElement;
        "bw-input": HTMLBwInputElement;
        "bw-modal": HTMLBwModalElement;
        "bw-nav": HTMLBwNavElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface BwBtn {
        /**
          * @default "#"
         */
        "link"?: string;
        /**
          * @default "Name"
         */
        "name"?: string;
        "onClick"?: (event: BwBtnCustomEvent<void>) => void;
    }
    interface BwCard {
        "description": string;
        /**
          * @default 200
         */
        "descriptionLength"?: number;
        "imgAlt": string;
        "imgSrc": string;
        /**
          * @default '#'
         */
        "link"?: string;
        "name": string;
        /**
          * @default true
         */
        "populate"?: boolean;
        /**
          * @default true
         */
        "showBtn"?: boolean;
        /**
          * @default 'Tags:'
         */
        "tagTitle"?: string;
        "tags": string[];
    }
    interface BwContainer {
        /**
          * @default false
         */
        "grid"?: boolean;
        /**
          * @default "0px"
         */
        "mg"?: string;
        /**
          * @default "10px"
         */
        "pd"?: string;
        /**
          * @default false
         */
        "primary"?: boolean;
    }
    interface BwInput {
        /**
          * @default '0px'
         */
        "boxMg"?: string;
        "boxMgH": string;
        "boxMgV": string;
        /**
          * @default '0px'
         */
        "boxPd"?: string;
        "boxPdH": string;
        "boxPdV": string;
        /**
          * @default 5
         */
        "col"?: number;
        /**
          * @default 'Name'
         */
        "label"?: string;
        /**
          * @default false
         */
        "labelBold"?: boolean;
        /**
          * @default '1.5rem'
         */
        "labelSize"?: string;
        /**
          * @default '0px'
         */
        "mg"?: string;
        "onChangedValue"?: (event: BwInputCustomEvent<{ oldValue: string; newValue: string }>) => void;
        /**
          * @default '5px'
         */
        "pd"?: string;
        /**
          * @default 'Type Something'
         */
        "placeholder"?: string;
        /**
          * @default 5
         */
        "row"?: number;
        /**
          * @default '1rem'
         */
        "size"?: string;
        /**
          * @default false
         */
        "textarea"?: boolean;
        /**
          * @default 'type'
         */
        "type"?: string;
    }
    interface BwModal {
        /**
          * @default false
         */
        "isOpen"?: boolean;
        /**
          * @default ''
         */
        "name"?: string;
        "onModalClosed"?: (event: BwModalCustomEvent<void>) => void;
    }
    interface BwNav {
        /**
          * @default { name: 'Navbar', link: '#' }
         */
        "homeLink"?: ILink;
        /**
          * @default '0px'
         */
        "mg"?: string;
        /**
          * @default [     { name: 'Search', link: '#' },     { name: 'Manage', link: '#' },     { name: 'About', link: '#' },     { name: 'Profile', link: '#' },   ]
         */
        "navLinks"?: Array<ILink>;
        /**
          * @default '10px'
         */
        "pd"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }

    interface BwBtnAttributes {
        "name": string;
        "link": string;
    }
    interface BwCardAttributes {
        "populate": boolean;
        "imgSrc": string;
        "imgAlt": string;
        "showBtn": boolean;
        "name": string;
        "description": string;
        "descriptionLength": number;
        "tagTitle": string;
        "link": string;
    }
    interface BwContainerAttributes {
        "mg": string;
        "pd": string;
        "primary": boolean;
        "grid": boolean;
    }
    interface BwInputAttributes {
        "boxMg": string;
        "boxMgH": string;
        "boxMgV": string;
        "boxPd": string;
        "boxPdH": string;
        "boxPdV": string;
        "mg": string;
        "pd": string;
        "size": string;
        "labelSize": string;
        "labelBold": boolean;
        "label": string;
        "type": string;
        "placeholder": string;
        "textarea": boolean;
        "row": number;
        "col": number;
    }
    interface BwModalAttributes {
        "isOpen": boolean;
        "name": string;
    }
    interface BwNavAttributes {
        "mg": string;
        "pd": string;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }

    interface IntrinsicElements {
        "bw-btn": Omit<BwBtn, keyof BwBtnAttributes> & { [K in keyof BwBtn & keyof BwBtnAttributes]?: BwBtn[K] } & { [K in keyof BwBtn & keyof BwBtnAttributes as `attr:${K}`]?: BwBtnAttributes[K] } & { [K in keyof BwBtn & keyof BwBtnAttributes as `prop:${K}`]?: BwBtn[K] };
        "bw-card": Omit<BwCard, keyof BwCardAttributes> & { [K in keyof BwCard & keyof BwCardAttributes]?: BwCard[K] } & { [K in keyof BwCard & keyof BwCardAttributes as `attr:${K}`]?: BwCardAttributes[K] } & { [K in keyof BwCard & keyof BwCardAttributes as `prop:${K}`]?: BwCard[K] } & OneOf<"imgSrc", BwCard["imgSrc"], BwCardAttributes["imgSrc"]> & OneOf<"imgAlt", BwCard["imgAlt"], BwCardAttributes["imgAlt"]> & OneOf<"name", BwCard["name"], BwCardAttributes["name"]> & OneOf<"description", BwCard["description"], BwCardAttributes["description"]>;
        "bw-container": Omit<BwContainer, keyof BwContainerAttributes> & { [K in keyof BwContainer & keyof BwContainerAttributes]?: BwContainer[K] } & { [K in keyof BwContainer & keyof BwContainerAttributes as `attr:${K}`]?: BwContainerAttributes[K] } & { [K in keyof BwContainer & keyof BwContainerAttributes as `prop:${K}`]?: BwContainer[K] };
        "bw-input": Omit<BwInput, keyof BwInputAttributes> & { [K in keyof BwInput & keyof BwInputAttributes]?: BwInput[K] } & { [K in keyof BwInput & keyof BwInputAttributes as `attr:${K}`]?: BwInputAttributes[K] } & { [K in keyof BwInput & keyof BwInputAttributes as `prop:${K}`]?: BwInput[K] } & OneOf<"boxMgH", BwInput["boxMgH"], BwInputAttributes["boxMgH"]> & OneOf<"boxMgV", BwInput["boxMgV"], BwInputAttributes["boxMgV"]> & OneOf<"boxPdH", BwInput["boxPdH"], BwInputAttributes["boxPdH"]> & OneOf<"boxPdV", BwInput["boxPdV"], BwInputAttributes["boxPdV"]>;
        "bw-modal": Omit<BwModal, keyof BwModalAttributes> & { [K in keyof BwModal & keyof BwModalAttributes]?: BwModal[K] } & { [K in keyof BwModal & keyof BwModalAttributes as `attr:${K}`]?: BwModalAttributes[K] } & { [K in keyof BwModal & keyof BwModalAttributes as `prop:${K}`]?: BwModal[K] };
        "bw-nav": Omit<BwNav, keyof BwNavAttributes> & { [K in keyof BwNav & keyof BwNavAttributes]?: BwNav[K] } & { [K in keyof BwNav & keyof BwNavAttributes as `attr:${K}`]?: BwNavAttributes[K] } & { [K in keyof BwNav & keyof BwNavAttributes as `prop:${K}`]?: BwNav[K] };
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bw-btn": LocalJSX.IntrinsicElements["bw-btn"] & JSXBase.HTMLAttributes<HTMLBwBtnElement>;
            "bw-card": LocalJSX.IntrinsicElements["bw-card"] & JSXBase.HTMLAttributes<HTMLBwCardElement>;
            "bw-container": LocalJSX.IntrinsicElements["bw-container"] & JSXBase.HTMLAttributes<HTMLBwContainerElement>;
            "bw-input": LocalJSX.IntrinsicElements["bw-input"] & JSXBase.HTMLAttributes<HTMLBwInputElement>;
            "bw-modal": LocalJSX.IntrinsicElements["bw-modal"] & JSXBase.HTMLAttributes<HTMLBwModalElement>;
            "bw-nav": LocalJSX.IntrinsicElements["bw-nav"] & JSXBase.HTMLAttributes<HTMLBwNavElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
